name: Deploy model
description: deploy model using seldon core

inputs:
  - { name: model_uri, type: String, description: 'MLFlow model artifact URI' }

implementation:
  container:
    image: minio999/kubeflow-seldon@sha256:dc241b71182232d4deb35773e5f28c81436b0b4705a3f808112e82aae6316d4d
    command: [
      python3,
      src/deploy.py,
      --model_uri,
      { inputValue: model_uri }
    ]